apiVersion: v1
kind: Service
metadata:
  name: ocx-webhook
  namespace: ocx-system
  labels:
    app.kubernetes.io/name: ocx-webhook
    app.kubernetes.io/part-of: ocx-system
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - name: webhook
    port: 443
    targetPort: webhook
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: metrics
    protocol: TCP
  selector:
    app.kubernetes.io/name: ocx-webhook
