apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "ocx-webhook.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: ocx-system
    {{- with .Values.namespaceSelector }}
    {{ .enforceLabel }}: {{ .enforceValue }}
    {{- end }}
