apiVersion: v1
kind: Secret
metadata:
  name: ocx-secrets
type: Opaque
stringData:
  api-keys: "dev123,prod456"
  db-url: "postgres://ocx:password@postgres-service:5432/ocx?sslmode=disable"
  signing-key: |
    -----BEGIN PRIVATE KEY-----
    # Replace with your actual signing key
    -----END PRIVATE KEY-----
